# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6d88f89706c5d9b827895c7f61f077000e1de0498f40e542eaf30263092e3600b7d3cfefce97c3699efeaae6b444497f883567875cf3b18d961949632694a577

test:
  secret_key_base: fb806142a7183769514e010ea6aa4d8a846db1fbf569cd4eb97f26b5167f22da9f4373a0dabb908a9cc28ad586138433b7636199ebe938a201185625409fed46

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
